kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-frontend
  labels:
    {{- include "qotd.labels" . | nindent 4 }}
    app: qotd-frontend
spec:
  to:
    kind: Service
    name: qotd-frontend
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
