kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: qotd-csharp
  labels:
    {{- include "qotd.labels" . | nindent 4 }}
    app: qotd-csharp
spec:
  to:
    kind: Service
    name: qotd-csharp
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
